# Settings
title: "Personal space"
description: "My personal space"
keywords: "minimoe,minimoes"
author: "Joakim Bick"
baseurl: ""
url: "http://minimoe.github.com"
github_username: minimoe
twitter_username: minimoe

# Build settings
gems:
    - jekyll-feed
exclude: 
    - README.md
    - Gemfile
    - Gemfile.lock 
markdown: kramdown
theme: minima
